/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_input_free(a: number): void;
export function input_name(a: number): number;
export function input_ty(a: number): number;
export function input_value(a: number): number;
export function input_min(a: number): number;
export function input_max(a: number): number;
export function input_default(a: number): number;
export function __wbg_messagequeue_free(a: number): void;
export function __wbg_inputlist_free(a: number): void;
export function inputlist_new(): number;
export function inputlist_clone(a: number): number;
export function inputlist_on_update(a: number, b: number): void;
export function inputlist_inputs(a: number, b: number): void;
export function messagequeue_new(): number;
export function messagequeue_clone(a: number): number;
export function messagequeue_update_value(a: number, b: number, c: number, d: number): void;
export function messagequeue_reload_code(a: number, b: number, c: number): void;
export function messagequeue_resize(a: number, b: number, c: number): void;
export function __wbg_app_free(a: number): void;
export function app_on_update(a: number, b: number): void;
export function app_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function app_run(a: number): number;
export function __wbg_ctx_free(a: number): void;
export function new_ctx(): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h80e7886da90bcdf9(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1bc83cc9560318f3(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha511fa6cd675de9c(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hcb133bbaa8fabdb6(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__he381cf16eb809268(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h8ad33c7e53e0bcfb(a: number, b: number, c: number, d: number): void;
